name: Build and Push Docker Image for the API and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: "contains(github.event.head_commit.message, 'docker')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push loginapp
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: pablo06/loginapp:latest, pablo06/loginapp:latest
